name: Deploy Plantotron 2
on:
  push:
    branches:
    - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        command: |
          cd /home/momo/plantotron
          git fetch
          git checkout $GITHUB_SHA
          /home/momo/.local/bin/poetry install -n --ansi --without=dev --sync
          POETRY_PYTHON="$(/home/momo/.local/bin/poetry run -n --ansi which python)"
          /usr/bin/sudo "${POETRY_PYTHON}" -m plantotron install
